const historicalAtlasData = [
  {
    id: "nixonschock",
    label: "Nixon Shock",
    year: "1971",
    startYear: 1971,
    description:
      "The United States ended the dollar's convertibility to gold, effectively collapsing the Bretton Woods fixed exchange rate system.",
    markets: "Gold +35%, USD volatility up, commodities up, FX markets expand.",
    drivers: ["Monetary policy shift", "Inflation pressure", "Currency regime change"],
    similarity: 40,
    color: "#F59E0B",
  },
  {
    id: "oilcrisis",
    label: "1973 Oil Crisis",
    year: "1973",
    startYear: 1973,
    description: "OPEC imposed an oil embargo on Western nations, causing a severe global energy shortage.",
    markets: "Oil +300-400%, global stocks -40%, inflation up, bond yields up.",
    drivers: ["Energy supply shock", "Geopolitical conflict"],
    similarity: 75,
    color: "#F97316",
  },
  {
    id: "globalstockmarketcrash",
    label: "1973-1974 Stock Market Crash",
    year: "1973",
    startYear: 1973,
    description: "A deep global recession combined with the oil crisis triggered a major global equity bear market.",
    markets: "Global equities -45%, unemployment up, commodities up.",
    drivers: ["Stagflation", "Recession", "Energy crisis"],
    similarity: 70,
    color: "#EF4444",
  },
  {
    id: "iranianoilcrisis",
    label: "1979 Oil Crisis",
    year: "1979",
    startYear: 1979,
    description: "The Iranian Revolution disrupted global oil production and caused a sharp spike in energy prices.",
    markets: "Oil +100%, gold +120%, equities down.",
    drivers: ["Energy supply disruption", "Geopolitical instability"],
    similarity: 78,
    color: "#FB7185",
  },
  {
    id: "latinamericandebtcrisis",
    label: "Latin American Debt Crisis",
    year: "1982",
    startYear: 1982,
    description: "Several Latin American countries defaulted on foreign debt after global interest rates surged.",
    markets: "Emerging market bonds -30%, banking losses up.",
    drivers: ["Debt overload", "Rising interest rates"],
    similarity: 65,
    color: "#8B5CF6",
  },
  {
    id: "plazaaccord",
    label: "Plaza Accord",
    year: "1985",
    startYear: 1985,
    description: "Major economies coordinated to weaken the U.S. dollar to correct global trade imbalances.",
    markets: "USD -40% vs yen, Japanese equities surge.",
    drivers: ["Government currency intervention", "Trade imbalance correction"],
    similarity: 55,
    color: "#A855F7",
  },
  {
    id: "blackmonday",
    label: "Black Monday",
    year: "1987",
    startYear: 1987,
    description: "Global equity markets collapsed in a single day due to automated trading and panic selling.",
    markets: "Dow Jones -22.6%, global equities -20-40%.",
    drivers: ["Program trading", "Liquidity shock", "Market panic"],
    similarity: 45,
    color: "#F43F5E",
  },
  {
    id: "japanassetbubblecollapse",
    label: "Japanese Asset Price Bubble Collapse",
    year: "1990",
    startYear: 1990,
    description: "Japan's massive stock and real estate bubble burst after years of speculation and credit expansion.",
    markets: "Nikkei -60%, real estate -80%.",
    drivers: ["Asset bubble burst", "Monetary tightening"],
    similarity: 60,
    color: "#E879F9",
  },
  {
    id: "bondmarketcrash",
    label: "1994 Bond Market Crash",
    year: "1994",
    startYear: 1994,
    description: "Rapid and unexpected interest rate hikes triggered large losses across global bond markets.",
    markets: "Global bonds -10-20%, yields up sharply.",
    drivers: ["Interest rate shock", "Monetary tightening"],
    similarity: 85,
    color: "#06B6D4",
  },
  {
    id: "mexicanpesocrisis",
    label: "Mexican Peso Crisis",
    year: "1994",
    startYear: 1994,
    description: "Mexico devalued the peso after its foreign reserves were depleted.",
    markets: "Peso -50%, emerging market equities down.",
    drivers: ["Currency crisis", "Capital flight"],
    similarity: 55,
    color: "#14B8A6",
  },
  {
    id: "asianfinancialcrisis",
    label: "Asian Financial Crisis",
    year: "1997",
    startYear: 1997,
    description: "Currency collapses spread across Southeast Asia following speculative attacks on the Thai baht.",
    markets: "Asian currencies -40-80%, regional equities -30-70%.",
    drivers: ["Currency speculation", "High foreign debt"],
    similarity: 65,
    color: "#0EA5E9",
  },
  {
    id: "russianfinancialcrisis",
    label: "Russian Financial Crisis",
    year: "1998",
    startYear: 1998,
    description: "Russia defaulted on sovereign debt and devalued the ruble, destabilizing global financial markets.",
    markets: "Ruble -70%, global equities -10%.",
    drivers: ["Sovereign default", "Commodity price collapse"],
    similarity: 70,
    color: "#38BDF8",
  },
  {
    id: "dotcombubble",
    label: "Dot-com Bubble",
    year: "1995-2000",
    startYear: 1995,
    description: "Investors heavily speculated on internet companies, pushing tech valuations to extreme levels.",
    markets: "NASDAQ +400%, tech IPO boom.",
    drivers: ["Technological hype", "Speculative investment"],
    similarity: 82,
    color: "#14B8A6",
  },
  {
    id: "dotcomcrash",
    label: "Dot-com Crash",
    year: "2000",
    startYear: 2000,
    description: "Technology stocks collapsed when many internet companies failed to produce sustainable profits.",
    markets: "NASDAQ -75%.",
    drivers: ["Overvaluation", "Speculative bubble burst"],
    similarity: 72,
    color: "#F97316",
  },
  {
    id: "septemberattacks",
    label: "September 11 Attacks",
    year: "2001",
    startYear: 2001,
    description: "Terrorist attacks in the United States disrupted global financial markets and economic activity.",
    markets: "US stocks -7%, airline stocks -30%, gold up.",
    drivers: ["Geopolitical shock", "Economic uncertainty"],
    similarity: 50,
    color: "#F59E0B",
  },
  {
    id: "commoditysupercycle",
    label: "Global Commodity Supercycle",
    year: "2003-2008",
    startYear: 2003,
    description: "Rapid industrial growth in China created massive demand for raw materials worldwide.",
    markets: "Copper +300%, oil +250%, mining stocks up.",
    drivers: ["Industrialization", "Infrastructure boom"],
    similarity: 68,
    color: "#10B981",
  },
  {
    id: "globalfinancialcrisis",
    label: "Global Financial Crisis",
    year: "2007-2009",
    startYear: 2007,
    description: "The collapse of the U.S. housing bubble triggered a global banking and credit crisis.",
    markets: "Global equities -50%, oil -70%, gold +25%.",
    drivers: ["Housing bubble burst", "Excessive leverage", "Banking failures"],
    similarity: 62,
    color: "#60A5FA",
  },
  {
    id: "europeandebtcrisis",
    label: "European Sovereign Debt Crisis",
    year: "2010",
    startYear: 2010,
    description: "Several European countries struggled with unsustainable government debt levels.",
    markets: "European bank stocks -40%, euro down, bond yields up.",
    drivers: ["Sovereign debt crisis", "Fiscal instability"],
    similarity: 70,
    color: "#38BDF8",
  },
  {
    id: "flashcrash",
    label: "2010 Flash Crash",
    year: "2010",
    startYear: 2010,
    description: "Algorithmic trading triggered a rapid and temporary collapse in U.S. equity markets.",
    markets: "Dow -9% intraday.",
    drivers: ["High-frequency trading", "Liquidity vacuum"],
    similarity: 45,
    color: "#22C55E",
  },
  {
    id: "arabspring",
    label: "Arab Spring",
    year: "2011",
    startYear: 2011,
    description: "Political uprisings across the Middle East destabilized governments and energy supply chains.",
    markets: "Oil +20%, gold up.",
    drivers: ["Political instability", "Energy supply risk"],
    similarity: 75,
    color: "#F97316",
  },
  {
    id: "chinastockmarketcrash",
    label: "2015-2016 Chinese Stock Market Turbulence",
    year: "2015",
    startYear: 2015,
    description: "China's stock market surged and collapsed rapidly due to speculative investment.",
    markets: "Shanghai Composite -30%.",
    drivers: ["Speculative bubble", "Policy intervention"],
    similarity: 65,
    color: "#A855F7",
  },
  {
    id: "brexit",
    label: "Brexit Referendum",
    year: "2016",
    startYear: 2016,
    description: "The United Kingdom voted to leave the European Union, creating major economic uncertainty.",
    markets: "GBP -10%, global stocks -3-5%, gold +8%.",
    drivers: ["Political uncertainty", "Trade disruption"],
    similarity: 60,
    color: "#14B8A6",
  },
  {
    id: "chinatradewar",
    label: "China-United States Trade War",
    year: "2018",
    startYear: 2018,
    description: "Tariffs between the U.S. and China disrupted global trade and supply chains.",
    markets: "Global equities -10%, commodities volatility up.",
    drivers: ["Protectionism", "Geopolitical competition"],
    similarity: 88,
    color: "#06B6D4",
  },
  {
    id: "covidpandemic",
    label: "COVID-19 Pandemic",
    year: "2020",
    startYear: 2020,
    description: "Global lockdowns halted economic activity and caused the fastest stock market crash in history.",
    markets: "Global stocks -35%, oil -65%, gold +25%.",
    drivers: ["Economic shutdown", "Demand collapse"],
    similarity: 50,
    color: "#8B5CF6",
  },
  {
    id: "supplychaincrisis",
    label: "Global Supply Chain Crisis",
    year: "2020",
    startYear: 2020,
    description: "Pandemic disruptions caused severe shortages in shipping, semiconductors, and manufacturing inputs.",
    markets: "Freight rates +500%, inflation up globally.",
    drivers: ["Logistics disruptions", "Production shortages"],
    similarity: 80,
    color: "#06B6D4",
  },
  {
    id: "ukrainewar",
    label: "Russian Invasion of Ukraine",
    year: "2022",
    startYear: 2022,
    description: "Russia's invasion disrupted global energy and grain supplies.",
    markets: "Oil +60%, wheat +40%, European stocks -15%.",
    drivers: ["War", "Sanctions", "Energy supply shock"],
    similarity: 90,
    color: "#F97316",
  },
  {
    id: "globalinflationshock",
    label: "Global Inflation & Interest Rate Shock",
    year: "2022",
    startYear: 2022,
    description: "Central banks rapidly increased interest rates to combat high inflation.",
    markets: "Bonds -20%, tech stocks -30%, USD up.",
    drivers: ["Inflation surge", "Monetary tightening"],
    similarity: 95,
    color: "#F59E0B",
  },
  {
    id: "bankingcrisis",
    label: "2023 Banking Crisis",
    year: "2023",
    startYear: 2023,
    description: "Several regional banks collapsed due to liquidity stress and rising interest rates.",
    markets: "Bank stocks -20-40%, gold up.",
    drivers: ["Liquidity risk", "Interest rate exposure"],
    similarity: 92,
    color: "#22C55E",
  },
  {
    id: "aiinvestmentboom",
    label: "AI Investment Boom",
    year: "2023",
    startYear: 2023,
    description: "Massive global investment in artificial intelligence technologies fueled a surge in tech valuations.",
    markets: "Semiconductor stocks +100-300%, tech indices up.",
    drivers: ["Technological innovation", "Capital inflows"],
    similarity: 98,
    color: "#10B981",
  },
  {
    id: "middleeastconflict",
    label: "Rising Middle East Conflict",
    year: "2026",
    startYear: 2026,
    description: "Geopolitical tensions threaten oil supply routes.",
    markets: "Oil +20-30%, stocks down short-term.",
    drivers: ["Geopolitics", "Energy supply risk"],
    similarity: 94,
    color: "#F97316",
  },
];

export default historicalAtlasData;
